# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.private_key_path="~/.vagrant.d/insecure_private_key"
  
  config.vm.define "esxi" do |vmcfg|
    vmcfg.vm.box = "bravostudiodev/esxi"
    vmcfg.vm.hostname = "esxi"
    if Vagrant.has_plugin?("vagrant-vbguest")
      vmcfg.vbguest.auto_update = false
    end
  end
end
