# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/shared", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/shared"
  end
  config.vm.define "godev" do |d|
    d.vm.box = "ubuntu/trusty64"
    d.vm.hostname = "godev"
	d.vm.provision :shell, path: "bootstrap_go.sh"
    d.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  end
  
  config.ssh.insert_key = false
  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end
