# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/shared", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/shared"
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path="~/.vagrant.d/insecure_private_key"

  config.vm.define "pachyderm" do |vmcfg|
    vmcfg.vm.box = "flixtech/kubernetes"
    vmcfg.vm.hostname = "pachyderm"
    if Vagrant.has_plugin?("vagrant-vbguest")
      vmcfg.vbguest.auto_update = false
    end
    vmcfg.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    vmcfg.vm.provision :shell, path: "bootstrap_pachyderm.sh"
  end
end
