# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/shared", mount_options: ["dmode=777,fmode=777"]
  else
    config.vm.synced_folder ".", "/shared"
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path="~/.vagrant.d/insecure_private_key"

  config.vm.define "selenium" do |vmcfg|
    vmcfg.vm.hostname = "selenium"
    vmcfg.vm.box = "boxcutter/ubuntu1604"
    
    vmcfg.vm.network :forwarded_port, guest:4444, host:14444
    # IMPORTANT: For embedded proxy to be accessible, you must allow incomming firewall rule from this IP on host
    # sudo iptables -A INPUT -s 192.168.33.0/24 -j ACCEPT
    # sudo iptables -A OUTPUT -d 192.168.33.0/24 -j ACCEPT
    # sudo iptables save
    # or
    # sudo ufw allow from 192.168.33.0/24 to 192.168.33.1
    # sudo ufw allow from 192.168.33.1 to 192.168.33.0/24
    vmcfg.vm.network :private_network, ip: "192.168.33.10"
    vmcfg.vm.provision :shell, inline: <<-SHELL
export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true
export TERM=linux
source /shared/bootstrap_00base.sh
source /shared/bootstrap_01xpra.sh
source /shared/bootstrap_02firefox.sh
source /shared/bootstrap_03chrome.sh
source /shared/bootstrap_04selenium.sh
mkdir -p /opt/selenium
cp /shared/selenium_entry.sh /opt/selenium/
chmod a+x /opt/selenium/selenium_entry.sh

addgroup uinput
usermod -a -G xpra,tty,video,dialout,uinput vagrant

apt-get update
apt-get install -qqy --no-install-recommends xserver-xorg-legacy
rm -rf /var/lib/apt/lists/* /var/cache/apt/*
touch /etc/X11/Xwrapper.config
echo "needs_root_rights=yes" >> /etc/X11/Xwrapper.config

cat > /etc/systemd/system/xpraonboot.service << "EOF"
[Unit]
Description=xpra as user
After=getty@tty7.service

[Service]
Type=simple
User=vagrant
ExecStart=/opt/selenium/selenium_entry.sh
StandardInput=tty
TTYPath=/dev/tty7
TTYReset=yes
TTYVHangup=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl disable xpra
systemctl enable xpraonboot
systemctl start xpraonboot

SHELL

    vmcfg.vm.provision :reload # Requires: vagrant plugin install vagrant-reload

    if Vagrant.has_plugin?("vagrant-vbguest")
      vmcfg.vbguest.auto_update = false
    end

    vmcfg.vm.provider :virtualbox do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.gui = true
      vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']  
    end
  end

  config.vm.define "winselenium" do |vmcfg|
    vmcfg.vm.box = "bravostudiodev/win10box"
    vmcfg.vm.hostname = "winselenium"
    vmcfg.ssh.private_key_path="~/.vagrant.d/insecure_private_key"
    # IMPORTANT: For embedded proxy to be accessible, you must allow incomming firewall rule from this IP on host
    # sudo iptables -A INPUT -s 192.168.33.0/24 -j ACCEPT
    # sudo iptables -A OUTPUT -d 192.168.33.0/24 -j ACCEPT
    # sudo iptables save
    # or
    # sudo ufw allow from 192.168.33.0/24 to 192.168.33.1
    # sudo ufw allow from 192.168.33.1 to 192.168.33.0/24
    vmcfg.vm.network :private_network, ip: "192.168.33.20"
    vmcfg.vm.provision :shell, path: "bootstrap_selenium.ps1"
    vmcfg.vm.provision :shell, inline: <<-SHELL
function EnsureKey {
  $item = $args[0]
  if (!(Test-Path $item)) { New-Item $item -ItemType RegistryKey -Force | Out-Default }
}
$keyWinlogon = 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon'
EnsureKey $keyWinlogon
Set-ItemProperty -Path $keyWinlogon -Name AutoAdminLogon -Type "DWord" -Value 1 -Force | Out-Default
Set-ItemProperty -Path $keyWinlogon -Name DefaultUserName -Value "vagrant" -Force | Out-Default
Set-ItemProperty -Path $keyWinlogon -Name DefaultPassword -Value "vagrant" -Force | Out-Default

SHELL

    vmcfg.vm.provision :reload # Requires: vagrant plugin install vagrant-reload

    if Vagrant.has_plugin?("vagrant-vbguest")
      vmcfg.vbguest.auto_update = false
    end
  end

  # https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
  # https://az792536.vo.msecnd.net/vms/VMBuild_20171019/Vagrant/MSEdge/MSEdge.Win10.Vagrant.zip
  # vagrant box add --name "Microsoft/EdgeOnWindows10" /mnt/data/vagrant\ boxes/MsEdge\ -\ Win10.box
  # IMPORTANT: Manual steps needed in VM on first run:
  #  1. Update VirtualBoxGuestAddition to match version at host
  #  2. Download VM winrm-enable.cmd from https://gist.github.com/gorvin/ed0b8b9738768f10e9ad7c9766ba5dcb
  #  3. Open cmd.exe with elevated privileges and execute winrm-enable.cmd
  #  4. Go back to host and execute vagrant up --provision winhodor
  config.vm.define "winhodor" do |vmcfg|
    vmcfg.vm.box = "Microsoft/EdgeOnWindows10"
    vmcfg.vm.hostname = "winhodor"
    vmcfg.vm.guest = :windows
    vmcfg.vm.communicator = "winrm"
    vmcfg.winrm.username = "IEUser"
    vmcfg.winrm.password = "Passw0rd!"
    vmcfg.windows.halt_timeout = 15
    vmcfg.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    # vmcfg.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    vmcfg.vm.network :private_network, ip: "192.168.33.30"
    vmcfg.vm.provision :shell, path: "bootstrap_selenium.ps1"
    # vmcfg.vm.provision :reload

    if Vagrant.has_plugin?("vagrant-vbguest")
      vmcfg.vbguest.auto_update = false
    end
  end

end
